# Generated by Django 3.2.9 on 2022-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_note_json_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='github_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
